apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: db
  template:
    metadata:
      labels:
        app: wordpress
        tier: db
    spec:
      containers:
        - name: wordpress-db
          image: mariadb:10.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-db
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: app
  template:
    metadata:
      labels:
        app: wordpress
        tier: app
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.5.3-apache
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-db
            - name: WORDPRESS_DB_PASSWORD
              value: password

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-np
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: wordpress
    tier: app
