apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-dp
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v1
---
# ClusterIP까지 필요한 줄 알았으나 필요없음.
# 내부의 다른 팟에게 연결할 것이 아니므로 불필요.

# apiVersion: v1
# kind: Service
# metadata:
#   name: echo-ci
#   labels:
#     app: echo
# spec:
#   ports:
#     - port: 3000
#       protocol: TCP
#   selector:
#     app: echo
---
apiVersion: v1
kind: Service
metadata:
  name: echo-np
  labels:
    app: echo
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 32000
  selector:
    app: echo
