version: "3"
services:
  vote:
    build: ./vote
    ports:
      - "60001:80"
  redis:
    image: redis:alpine
  worker:
    build: ./worker
  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  result:
    build: ./result
    ports:
      - "60002:80"
